version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DATABASE_HOST: ""
      DATABASE_NAME: ""
      DATABASE_USERNAME: ""
      DATABASE_PASSWORD: ""
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432" 
    networks:
      - hajki_shared_network

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/hajki_db_dev
      RAILS_ENV: development
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY_ID: ""
      AWS_REGION: ""
      AWS_BUCKET: hajki-api
    networks:
      - hajki_shared_network

networks:
  hajki_shared_network:
    external: true

volumes:
  db-data:
